import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen bg-zinc-50">
          <Navbar />
          <main className="flex flex-1 py-10">
            <div className="flex-1 px-14">{children}</div>
          </main>
        </div>
        <div>
          <Toaster position="top-right" />
        </div>
      </body>
    </html>
  );
}
